/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ApplicationStatusRouteImport } from './routes/application-status'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenturesIndexRouteImport } from './routes/ventures.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VenturesSlugRouteImport } from './routes/ventures.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AboutStandardsRouteImport } from './routes/about.standards'
import { Route as AboutMethodologyRouteImport } from './routes/about.methodology'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as AboutAwardsRouteImport } from './routes/about.awards'
import { Route as AboutPillarRouteImport } from './routes/about.$pillar'
import { Route as AdminCmsTypeRouteImport } from './routes/admin.cms.$type'
import { Route as AdminCmsTypeIdRouteImport } from './routes/admin.cms.$type.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationStatusRoute = ApplicationStatusRouteImport.update({
  id: '/application-status',
  path: '/application-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesIndexRoute = VenturesIndexRouteImport.update({
  id: '/ventures/',
  path: '/ventures/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesSlugRoute = VenturesSlugRouteImport.update({
  id: '/ventures/$slug',
  path: '/ventures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin/cms',
  path: '/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutStandardsRoute = AboutStandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMethodologyRoute = AboutMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAwardsRoute = AboutAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AboutRoute,
} as any)
const AboutPillarRoute = AboutPillarRouteImport.update({
  id: '/$pillar',
  path: '/$pillar',
  getParentRoute: () => AboutRoute,
} as any)
const AdminCmsTypeRoute = AdminCmsTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsTypeIdRoute = AdminCmsTypeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCmsTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/$pillar': typeof AboutPillarRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/about/standards': typeof AboutStandardsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ventures/': typeof VenturesIndexRoute
  '/admin/cms/$type': typeof AdminCmsTypeRouteWithChildren
  '/admin/cms/$type/$id': typeof AdminCmsTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/$pillar': typeof AboutPillarRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/about/standards': typeof AboutStandardsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ventures': typeof VenturesIndexRoute
  '/admin/cms/$type': typeof AdminCmsTypeRouteWithChildren
  '/admin/cms/$type/$id': typeof AdminCmsTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/about/$pillar': typeof AboutPillarRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/methodology': typeof AboutMethodologyRoute
  '/about/standards': typeof AboutStandardsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ventures/$slug': typeof VenturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ventures/': typeof VenturesIndexRoute
  '/admin/cms/$type': typeof AdminCmsTypeRouteWithChildren
  '/admin/cms/$type/$id': typeof AdminCmsTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/application-status'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/about/$pillar'
    | '/about/awards'
    | '/about/leadership'
    | '/about/methodology'
    | '/about/standards'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/login'
    | '/admin/messages'
    | '/careers/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/ventures/$slug'
    | '/admin/'
    | '/ventures/'
    | '/admin/cms/$type'
    | '/admin/cms/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/application-status'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/about/$pillar'
    | '/about/awards'
    | '/about/leadership'
    | '/about/methodology'
    | '/about/standards'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/login'
    | '/admin/messages'
    | '/careers/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/ventures/$slug'
    | '/admin'
    | '/ventures'
    | '/admin/cms/$type'
    | '/admin/cms/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/application-status'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/about/$pillar'
    | '/about/awards'
    | '/about/leadership'
    | '/about/methodology'
    | '/about/standards'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/login'
    | '/admin/messages'
    | '/careers/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/ventures/$slug'
    | '/admin/'
    | '/ventures/'
    | '/admin/cms/$type'
    | '/admin/cms/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  ApplicationStatusRoute: typeof ApplicationStatusRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  InsightsRoute: typeof InsightsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  VenturesSlugRoute: typeof VenturesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  VenturesIndexRoute: typeof VenturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-status': {
      id: '/application-status'
      path: '/application-status'
      fullPath: '/application-status'
      preLoaderRoute: typeof ApplicationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/': {
      id: '/ventures/'
      path: '/ventures'
      fullPath: '/ventures/'
      preLoaderRoute: typeof VenturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures/$slug': {
      id: '/ventures/$slug'
      path: '/ventures/$slug'
      fullPath: '/ventures/$slug'
      preLoaderRoute: typeof VenturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/standards': {
      id: '/about/standards'
      path: '/standards'
      fullPath: '/about/standards'
      preLoaderRoute: typeof AboutStandardsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/methodology': {
      id: '/about/methodology'
      path: '/methodology'
      fullPath: '/about/methodology'
      preLoaderRoute: typeof AboutMethodologyRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/awards': {
      id: '/about/awards'
      path: '/awards'
      fullPath: '/about/awards'
      preLoaderRoute: typeof AboutAwardsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/$pillar': {
      id: '/about/$pillar'
      path: '/$pillar'
      fullPath: '/about/$pillar'
      preLoaderRoute: typeof AboutPillarRouteImport
      parentRoute: typeof AboutRoute
    }
    '/admin/cms/$type': {
      id: '/admin/cms/$type'
      path: '/$type'
      fullPath: '/admin/cms/$type'
      preLoaderRoute: typeof AdminCmsTypeRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/$type/$id': {
      id: '/admin/cms/$type/$id'
      path: '/$id'
      fullPath: '/admin/cms/$type/$id'
      preLoaderRoute: typeof AdminCmsTypeIdRouteImport
      parentRoute: typeof AdminCmsTypeRoute
    }
  }
}

interface AboutRouteChildren {
  AboutPillarRoute: typeof AboutPillarRoute
  AboutAwardsRoute: typeof AboutAwardsRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutMethodologyRoute: typeof AboutMethodologyRoute
  AboutStandardsRoute: typeof AboutStandardsRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutPillarRoute: AboutPillarRoute,
  AboutAwardsRoute: AboutAwardsRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutMethodologyRoute: AboutMethodologyRoute,
  AboutStandardsRoute: AboutStandardsRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface CareersRouteChildren {
  CareersSlugRoute: typeof CareersSlugRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSlugRoute: CareersSlugRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface AdminCmsTypeRouteChildren {
  AdminCmsTypeIdRoute: typeof AdminCmsTypeIdRoute
}

const AdminCmsTypeRouteChildren: AdminCmsTypeRouteChildren = {
  AdminCmsTypeIdRoute: AdminCmsTypeIdRoute,
}

const AdminCmsTypeRouteWithChildren = AdminCmsTypeRoute._addFileChildren(
  AdminCmsTypeRouteChildren,
)

interface AdminCmsRouteChildren {
  AdminCmsTypeRoute: typeof AdminCmsTypeRouteWithChildren
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsTypeRoute: AdminCmsTypeRouteWithChildren,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  ApplicationStatusRoute: ApplicationStatusRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  InsightsRoute: InsightsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCmsRoute: AdminCmsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  VenturesSlugRoute: VenturesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  VenturesIndexRoute: VenturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
